server:
  port: ${PORT:18081}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:/}

spring:
  application:
    name: Backend_UserService

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER:165.192.105.57}:${DB_PORT:31029}/${DB_NAME:kbt1}?useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME:faker}
    password: ${DB_PASSWORD:kbt1Best!}
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug